location /app {
    proxy_pass https://reverb-ws.glitter.tw;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";

    proxy_set_header Host reverb-ws.glitter.tw;
    proxy_read_timeout 60s;
    proxy_send_timeout 60s;
}
